# web server
nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # app
    - $HOME/kindle_web_react:/usr/share/nginx/html
    - $HOME/kindle-restapi:/usr/share/nginx/app
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
  links:
    - fpm:__DOCKER_PHP_FPM__

# php-fpm
fpm:
  image: wudizhuo/php_postfix_kindlegen:V1