# web server
nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # app
    - /home/ubuntu/kindle_web_react:/usr/share/nginx/html
    - /home/ubuntu/kindle-restapi:/usr/share/nginx/app
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro